version: '3.3'

services:

  database:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - database
    ports:
      - "8200:8181"
    restart: unless-stopped
